### ISSUE TITLE
Kubefirst mongodb Username and Password not set for arm builds

### ISSUE THREAD

**Issue by EamonKeane** [kubefirst/gitops-template#576]
I think there might be a bug when using kubefirst for mongodb with arm on 2.2.17. As bitnami don't have an arm image, the gitops catalogue uses the official mongo one. However the official mongo image looks for different env vars for the username and password (`MONGO_INITDB_ROOT_USERNAME` for the [official image](https://hub.docker.com/_/mongo) but `MONGO_ROOT_USER` for [bitnami](https://hub.docker.com/r/bitnami/mongodb) as they appear to have some extra logic for primary vs secondary). Specifically, I think the env vars for k3d-arm need to be like so:

`helm install mongo-test --version 13.18.1  oci://registry-1.docker.io/bitnamicharts/mongodb --namespace kubefirst  --set image.repository=arm64v8/mongo --set image.tag=7.0.1 --set persistence.mountPath=/data/db  --set "extraEnvVars[0].name=MONGO_INITDB_ROOT_USERNAME" --set "extraEnvVars[0].value=root" --set "extraEnvVars[1].name=MONGO_INITDB_ROOT_PASSWORD" --set "extraEnvVars[1].value=root"`

The env vars for the kubefirst 2.2.17 deployed console looks like the below which is ignored. No user is created and so the authentication fails after a pod restart.
```
    - name: MONGODB_ROOT_USER
      value: root
    - name: MONGODB_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          key: mongodb-root-password
          name: kubefirst-initial-secrets
```

If they were like this I think it works.

```
    - name: MONGODB_INIT_ROOT_USERNAME
      value: root
    - name: MONGODB_INIT_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          key: mongodb-root-password
          name: kubefirst-initial-secrets
```
